#!/bin/sh
# Install Scene for the current user, so the desktop's global shortcut runs
# the build in this working tree.
#
# This exists because two things bite during development, and neither is
# visible from the launcher:
#
#   1. `cargo build --release` writes target/release/scene, which is not the
#      binary a desktop entry runs. Without a reinstall the shortcut keeps
#      starting whatever was installed last.
#   2. Scene is a single-instance application. A resident process owns the
#      dev.scene.Scene name, so a newly started binary hands over to the old
#      one and exits. Replacing the file is not enough; the old process has to
#      go.
#
# It also generates the user desktop entry from data/dev.scene.Scene.desktop
# rather than leaving a hand-copied one to drift out of step with it. The
# packaged entry says `Exec=scene`, which is right for /usr/bin; a development
# install rewrites that to the absolute path of the binary it just installed,
# because a desktop session's PATH is not a login shell's.
#
# Packaging proper is Milestone 8. This is the development path only.

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
data_home=${XDG_DATA_HOME:-$HOME/.local/share}
cargo_home=${CARGO_INSTALL_ROOT:-${CARGO_HOME:-$HOME/.cargo}}
binary=$cargo_home/bin/scene
applications=$data_home/applications
metainfo=$data_home/metainfo

echo "Installing Scene from $root"

# Reuse the working tree's build cache rather than compiling the dependency
# tree a second time in cargo install's own directory.
CARGO_TARGET_DIR=$root/target cargo install --path "$root" --force --quiet
echo "  binary        $binary"

mkdir -p "$applications" "$metainfo"

entry=$applications/dev.scene.Scene.desktop
{
    echo "# Generated by scripts/install-user.sh from data/dev.scene.Scene.desktop."
    echo "# Edit the file in the repository, not this one."
    sed "s|^Exec=.*|Exec=$binary|" "$root/data/dev.scene.Scene.desktop"
} > "$entry"
echo "  desktop entry $entry"

cp "$root/data/dev.scene.Scene.metainfo.xml" "$metainfo/dev.scene.Scene.metainfo.xml"
echo "  metainfo      $metainfo/dev.scene.Scene.metainfo.xml"

if command -v desktop-file-validate >/dev/null 2>&1; then
    desktop-file-validate "$entry"
    echo "  desktop-file-validate: clean"
fi
if command -v appstreamcli >/dev/null 2>&1; then
    appstreamcli validate --no-net "$metainfo/dev.scene.Scene.metainfo.xml" >/dev/null
    echo "  appstreamcli validate: clean"
fi
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$applications" 2>/dev/null || true
fi

# Last, so the new binary is already in place when the old process goes.
if pkill -x scene 2>/dev/null; then
    echo "  stopped the resident instance, so the next activation starts this build"
fi

echo
echo "Done. Activate Scene with its configured shortcut."
echo "The packaged fallback is Meta+Space. KDE owns the active binding: open"
echo "Scene Settings with Ctrl+, to inspect it or launch KDE's recorder."
